### ISSUE TITLE
Systray and popup menu

### ISSUE THREAD

**Issue by nicolasbauw** [gabdube/native-windows-gui#123]
Hi,

Looks like I'm perfectionist, here are some details about systray and popup menu, that makes systray apps not behave like "usual" systray apps.
When the menu appears, the only way to make it disappear is to click on an item of the menu.
Usually with systray apps, when we click anywhere else on the screen, the menu disappears.

Also, the menu just appears with a right click, not with a left click.

I think that's because the systray menu behaves in fact like a regular window menu ?

**Comment by gabdube** [comment]
> I think that's because the systray menu behaves in fact like a regular window menu ?

Yes. The systray object raise the WM_CONTEXTMENU, which is the same message used on regular Windows. 

All of the systray app on my computer shows a menu with a right click, not with the left. 
Now that you mention it there's no way to bind a left click on a system tray. There's not much documentation of the events of system object, but I'll see what I can find

Didn't know about the menu that won't disappear until you select an item. I'll try to find out why it behaves that... probably because of the message window being set as a parent...

**Comment by gabdube** [comment]
well that was quick. `TrayNotification` implements the `MousePressLeftUp` event, I just forgot to document it.

**Comment by gabdube** [comment]
The menu staying up should be fixed with my last update

**Comment by nicolasbauw** [comment]
Everything is perfect.
- Indeed the menu is closing when we click anywhere else
- I used the OnMousePress event which triggers both buttons (it also works with MousePressLeftUp)

I see you already modified the systray example ;-)
