### ISSUE TITLE
consider adding simple custom dialog examples to the examples

### ISSUE THREAD

**Issue by sdicker8** [gabdube/native-windows-gui#170]
Hi Gabriel

I think a couple of custom dialog examples would be useful to users. I just started using nwg the other day and haven't been able to quickly figure out how to make a simple choice or text input child dialog. If/when i do, i'll likely be wondering if you would have done something differently. native-windows-derive is awesome, i'm thinking examples that use it would be really helpful.

This is a very nice crate, a real asset to the rust community - thanks!  :)

Scott

**Comment by gabdube** [comment]
I can do that 👍 , and it's been a while since I worked on NWG so I'll try to do this during the weekend

**Comment by gabdube** [comment]
I updated the multi-threaded dialog example:

https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/examples/dialog_multithreading_d.rs

There is currently no good way to dialog without multithreading because that would mean creating a new message loop inside a rust callback, and that would make things unstable. Common dialog are OK because all the code is on the Windows side.

**Comment by sdicker8** [comment]
Excellent - this is really helpful. Thank you -
