### ISSUE TITLE
Embedding png/jpg images

### ISSUE THREAD

**Issue by vikigenius** [gabdube/native-windows-gui#185]
I was following the embed resource example. Is it possible to embed a PNG/BMP image?

I tried converting the weird_cat.png to bitmap using an online converter and then tried to load that using the embed_resources example. But no image is shown (it is empty), and there was no error/warning either.

**Comment by gabdube** [comment]
If you use IMAGE (instead of BITMAP) as resource type in your `rc` file, native-windows-gui will use the image-decoder feature to load the image.  Ex:

`SUCCESS IMAGE "../resources/SUCCESS.png"`

If you want to load an IMAGE resource dynamically, you can use `image_str` ( https://docs.rs/native-windows-gui/1.0.11/native_windows_gui/struct.EmbedResource.html#method.image_str ).

As for why you couldn't load your converted image, it's probably because the bitmap version is not supported by `LoadImageW`, (the function that is used to load resources marked as "BITMAP"). Although it should raise an error. I will have to look into that.

**Comment by gabdube** [comment]
I guess this answered your question?
