### ISSUE TITLE
Naive end user - why the mispaint?

### ISSUE THREAD

**Issue by GregBowyer** [gabdube/native-windows-gui#239]
I am a total novice at windows UI so apologies if this seems trivial

Given the following:

```rust
use native_windows_gui as nwg;
use native_windows_derive as nwd;

use nwd::NwgUi;
use nwg::NativeUi;

#[derive(Default, NwgUi)]
pub struct App {
    #[nwg_control(size: (1000, 300), center: true, title: "Decrypter", flags: "WINDOW|VISIBLE")]
    #[nwg_events(OnWindowClose: [App::exit])]
    window: nwg::Window,

    #[nwg_layout(parent: window, max_row: Some(5), max_column: Some(2))]
    main_layout: nwg::GridLayout,

    #[nwg_control(text: "Decryption Key:")]
    #[nwg_layout_item(layout: main_layout, col:0, row: 0)]
    _lbl1: nwg::Label,

    #[nwg_control()]
    #[nwg_layout_item(layout: main_layout, col:1, row: 0)]
    decrypt_key: nwg::TextInput,

    #[nwg_control(text: "Sources:")]
    #[nwg_layout_item(layout: main_layout, col:0, row: 1)]
    _lbl2: nwg::Label,

    #[nwg_resource(title: "Select decryption key", filters: "Test(.zip.age)")]
    source_file_picker: nwg::FileDialog,

    #[nwg_control(text: "sources.zip.age")]
    #[nwg_layout_item(layout: main_layout, col:1, row: 1)]
    source_archive: nwg::TextInput,

    #[nwg_control(text: "Output:")]
    #[nwg_layout_item(layout: main_layout, col:0, row: 2)]
    _lbl3: nwg::Label,

    #[nwg_control(text: "sources")]
    #[nwg_layout_item(layout: main_layout, col:1, row: 2)]
    output_dir: nwg::TextInput,

    #[nwg_control(pos: 50)]
    #[nwg_layout_item(layout: main_layout, col_span: 2, row: 3)]
    progress: nwg::ProgressBar,

    #[nwg_control(text: "Exit",)]
    #[nwg_events(OnButtonClick: [App::exit])]
    #[nwg_layout_item(layout: main_layout, col:0, row: 4)]
    exit_button: nwg::Button,

    #[nwg_control(text: "Decrypt and extract", enabled: false)]
    #[nwg_events(OnButtonClick: [App::say_hello] )]
    #[nwg_layout_item(layout: main_layout, col:1, row: 4)]
    hello_button: nwg::Button,
}

impl App {
    fn say_hello(&self) {
        //nwg::simple_message("Hello", &format!("Hello {}", self.decrypt_key.text()));
    }

    fn exit(&self) {
        nwg::stop_thread_dispatch();
    }
}

fn main() {
    nwg::init().expect("Failed to init Native Windows GUI");

    let _app = App::build_ui(Default::default()).expect("Failed to build UI");

    nwg::dispatch_thread_events();
}
```

Why do the buttons paint in the top left corner?
![win-ui](https://user-images.githubusercontent.com/125935/151467793-6e5d889a-5033-431a-ac82-bbae7f59a04c.png)

**Comment by gabdube** [comment]
I can't reproduce the issue locally, but in win32 pixel m

You can try to add a `OnInit` event callback and call `[window.invalidate](https://docs.rs/native-windows-gui/1.0.12/native_windows_gui/struct.Window.html#method.invalidate)` inside it.

**Comment by NadyaNayme** [comment]
I believe I am having the same issue - or at least a related issue. 
Having an `OnInit` that calls `self.window.invalidate()` didn't fix it for me.

I'm having a similar mispaint on initial load when using `GridLayout` - when everything was positioned relative to `window` I wasn't having this issue. I have not tested if the issue persists when not using derives.
![image](https://user-images.githubusercontent.com/4567166/161414077-8984be02-cc9d-4cd4-ac02-673509b6df29.png)

Swapping tabs (which forces a redraw) fixes it:
![image](https://user-images.githubusercontent.com/4567166/161414080-6f8b22a1-eddc-49f7-8c52-76cee9dc8118.png)

Except in this weird scenario....
![image](https://user-images.githubusercontent.com/4567166/161414083-7d2993c3-e20a-4f64-a0ed-ea1f69a0743d.png)

The `export` button remains after a forced redraw when changing tabs to tabs _before_ the `Settings` tab.
![image](https://user-images.githubusercontent.com/4567166/161414086-a1cc3b70-117c-4837-b6d5-e4b7d59f1d08.png)

Changing the `Settings` tab to be the _first tab_ instead of the _last tab_ fixes the issue. If `Settings` is the third tab then the issue exists for the prior `Akasha` and `PBHL` tabs but _not_ for the `GOHL` tab which comes after. Which leads me to believe this bug might be sensitive to the order of the controls.

Video: https://kimiwo.aishitei.ru/i/3NDD0gOgmBQ9zUjT.mp4

**Comment by GregBowyer** [comment]
thanks
