### ISSUE TITLE
Providing shortcut for menu items

### ISSUE THREAD

**Issue by Warwolt** [gabdube/native-windows-gui#259]
In a lot of win32 programs there's context menus that provide a displayed shortcut for a given item (e.g. `Ctrl+X`) 

![image](https://user-images.githubusercontent.com/23612880/188290049-c85674c6-e030-458c-96e9-62a1413d3d99.png)

Is there anyway to provide such a shortcut text for `native_windows_gui::MenuItem`?

Edit: I think what I'm looking for is whether nwg has support for [Keyboard Accelerators](https://docs.microsoft.com/en-us/windows/apps/design/input/keyboard-accelerators)

**Comment by gabdube** [comment]
Sadly nwg doesn't support accelerators because the way they are implemented in win32 doesn't work well with how the library manages window handles. See https://docs.microsoft.com/en-us/windows/win32/learnwin32/accelerator-tables  .  

Basically I would either need to keep a reference to all the top level window in the windows message loop ("dispatch_thread_events" in nwg) and the only way to do that would be using a global static variable and somehow and plug it in the window creation procedure.

or I could re-implement the `TranslateAccelerator` function in pure rust, which sounds just as nightmarish as the last option.

**Comment by Warwolt** [comment]
Aha, actually I managed to find out what I actually needed here from this [stack overflow answer](https://stackoverflow.com/a/26846659):

![image](https://user-images.githubusercontent.com/23612880/188395285-2903bf73-2087-4f1f-b908-5caa68f426d3.png)

The shortcut _label_ is added by prefixing it with a tab `/t` character:

```rust
#[nwg_control(parent: file_menu, text: "E&xit\tAlt+F4")]
pub menu_item_exit: nwg::MenuItem,
```

It would be excellent if this would be added to the documentation for the `nwg::MenuItem`. I could open up a PR for this

**Comment by Warwolt** [comment]
Ok, I created a PR for this with #260

**Comment by gabdube** [comment]
Oh, well that's some great news! Thanks. And I will push a new release today to fix the freeze in the latest version.
