### ISSUE TITLE
SpVoice interface.

### ISSUE THREAD

**Issue by Eh2406** [gabdube/native-windows-gui#27]
Hi,

I have a windows gui written in rust that uses the [SpVoice](https://msdn.microsoft.com/en-us/library/ms723602.aspx) Interface. I use the `SetNotifyWindowMessage` to pass events back to my window. I'd love to be using the nwg, it looks way more ergonomic. I just cannot figure how to do that one peace. How do I listen for custom window messages?

Thanks!

**Comment by gabdube** [comment]
Sorry for the late response, I didn't see your issue until now.

As of the beta (the `v2` branch), the only way to catch custom events is too create a custom control and handle the events in the base window proc. I really want add the option to easily wrap new system events, 
but I can't decide the "best" way to do it.

**Comment by Eh2406** [comment]
How do I create a custom control? Is it worth figuring out how for `v2` with `v3` on the way?

**Comment by gabdube** [comment]
I've just added an example on v2: https://github.com/gabdube/native-windows-gui/blob/v2/examples/custom.rs

There won't be a `v3`. I had to rewrite the library once because I couldn't implement many features and a few controls (such as timer and menus). This time I made sure that  will be able to pack all the fancy features I want to include without any major breaking change.

**Comment by gabdube** [comment]
v2 is now on master and it will be on cargo soon enough.

Also, there is now `Event::Raw` implemented for most controls.  `Event::Raw`  will catch every single Windows message (that are not reserved by NWG) and pass the MSG, WPARAM, LPARAM to the callbacks. Until custom events are implemented, this will be the "best" way. 

Closing this...
