### ISSUE TITLE
Building using mingw

### ISSUE THREAD

**Issue by RazrFalcon** [gabdube/native-windows-gui#32]
Does it supported?

Currently I'm getting:
```
ld: cannot find -ld2d1
```

Windows 7 32bit

**Comment by gabdube** [comment]
I'm testing right now. It should be possible.

This error is raised because the direct2D library cannot be found. I've just learned that Direct2D was first introduced in Windows 8 but it was then backported to Windows 7. This might solve your problem: https://msdn.microsoft.com/en-us/library/windows/desktop/jj863687(v=vs.85).aspx

Hrmm, I will have to feature gate the canvas control...

**Comment by eugene-bulkin** [comment]
I'm getting this in Windows 10, too.

**Comment by gabdube** [comment]
@eugene-bulkin 

I know... Somehow mingw build cannot link/access `d2d1.lib` which is used by the canvas control.

**Comment by eugene-bulkin** [comment]
@gabdube Just wanted to clarify that it's present in a later version too, that's all!

**Comment by gabdube** [comment]
update. After feature gating the canvas, I've found that there was another error which was already referenced here (https://github.com/gabdube/native-windows-gui/issues/29). 

Currently this is my top priority. Hopefully, I'll be able to fix both issue or find a workaround.. otherwise NWG might be locked to msvc toolchains and that would suck.

**Comment by rkarp** [comment]
It looks like an executable needs to have a manifest to be able to use version 6 of comctl32 (see [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/bb773175(v=vs.85).aspx)). Doing this cleanly is blocked on [this RFC](https://github.com/rust-lang/rfcs/issues/721#issuecomment-71294242), though.

Cargo-update is using [this workaround](https://github.com/nabijaczleweli/cargo-update/blob/master/build.rs#L5) to embed a manifest, but I don't know if this is a good solution for NWG as a library.

**Comment by gabdube** [comment]
@RazrFalcon 
@eugene-bulkin 

Finally got myself to work on a workaround and it looks like it works (at least on my machine). If any of you are still interested just pull the `dev` branch and run `cargo run --example showcase`. :)

This should also allow cross-compilation from linux.

**Comment by RazrFalcon** [comment]
Great. Work for me, except `simple_canvas.rs`.

**Comment by gabdube** [comment]
Oh yeah, the canvas control is now behind the `canvas` feature because it requires d2d1.lib which is not included with the gnu version of rust.

if you want to run the example, 
Download `libd2d1.a` from https://github.com/retep998/winapi-rs/blob/dev/i686/lib/libd2d1.a
Copy it in your rust installation lib path. ie: `toolchains\stable-i686-pc-windows-gnu\lib\rustlib\i686-pc-windows-gnu\lib`
then run: `cargo run --example simple_canvas --features="canvas"`

and it should work
