### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by ark-** [gabdube/native-windows-gui#34]
A feature I noticed missing when using a UI made in NWG was drag and drop of text or files. e.g. dragging a text file into an input text box on a window and have the path filled out for me. I wondered if this was a possibility for this library.

I found the following links... if they're any use.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms645533(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/ms678405(v=vs.85).aspx
http://www.codeguru.com/cpp/misc/misc/draganddrop/article.php/c349/Drag-And-Drop-between-Window-Controls.htm

**Comment by gabdube** [comment]
Yes I think it will be possible. Its a bit more complicated than the average windows message, but I've seen worse.

**Comment by gabdube** [comment]
Added files drag and drop which should be enough for 1.0 See https://github.com/gabdube/native-windows-gui/blob/1.0-prerelease/native-windows-gui/examples/drop_files_d.rs

Custom drag and drop for control will be added post 1.0 because it looks like a lot of work. And I want to push the stable release sooner than later.

**Comment by lennartkloock** [comment]
Does this work in the other direction? Like dragging files or paths out of the window into another application like the Explorer.

**Comment by gabdube** [comment]
This is a one way direction, from an outside app to the rust app.
