### ISSUE TITLE
multiple windows in threads?

### ISSUE THREAD

**Issue by shiMusa** [gabdube/native-windows-gui#60]
Hi together,

I'm new to nwg, so maybe I missed the information, but when using a simple hello-world example I encountered the following issue:

The window is being created without issues in the main thread.
However, if I try to create a second window in a separate thread, I get errors of the kind

`thread '<unnamed>' panicked at 'Could not downcast command NWG_UNBIND args into a UnbindArgs struct.', C:\Users\...\github.com-1ecc6299db9ec823\native-windows-gui-0.2.0\src\low\message_handler.rs:174:17`

So, is multiple windows / multithreading implemented?
If yes, how do I have to setup the system?

Thanks and cheers!

**Comment by gabdube** [comment]
Hi, first and foremost, I've abandoned NWG a few months ago so I wound not recommend you to use NWG for any serious project.

As for the multithreaded problem, it was fixed in the dev branch ("0.3.0"), which is not available from cargo. Check out the changelog, if you are still interested https://github.com/gabdube/native-windows-gui/blob/dev/CHANGELOG.md
