### ISSUE TITLE
What happened? and, possibility of relicensing to more liberate license.

### ISSUE THREAD

**Issue by crlf0710** [gabdube/native-windows-gui#63]
Surprised to see this crate is not maintained any more. Any chance to re-license this code to something like MIT or Apache so others can pick this up and push it forward?

**Comment by gabdube** [comment]
The main reason is some serious flickering issues on bigger project, but also because winapi is pretty wonky in some place. Ultimately, the issues let me to believe that the amount of effort required to create something stable would not be worth it. But if you are still interested...

The `dev` branch license is MIT.
