### ISSUE TITLE
Are there any table view controls in this project?

### ISSUE THREAD

**Issue by chn-cutelotus** [gabdube/native-windows-gui#74]
Like the datagridview of MS .NET framework or tablewidget of QT?

**Comment by gabdube** [comment]
If you are on 1.0-prerelease branch, there will be one. It's called ListView and it wraps https://docs.microsoft.com/en-us/windows/win32/controls/list-view-controls-overview

The wrapper is not done yet (only the creation is done), but it's what I currently work on when I have the time.

Closing because this is related to #31

**Comment by gabdube** [comment]
The list view control has been implemented. You can see an example here: https://github.com/gabdube/native-windows-gui/blob/1.0-prerelease/native-windows-gui/examples/dataview_d.rs

also:

![dataview](https://user-images.githubusercontent.com/5180925/87874419-a85af780-c997-11ea-8b5e-5b41402fe5f2.PNG)
